FROM php:7.2-apache

COPY src/ /var/www/html/

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

ENV COMPOSER_ALLOW_SUPERUSER 1

COPY src/composer.json src/composer.lock ./

RUN composer install --no-plugins --no-scripts --optimize-autoloader --ignore-platform-req IGNORE-PLATFORM-REQ --prefer-dist

RUN composer dump-autoload

RUN php vendor/bin/phpunit